# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(840, 520)
        self.full_widget = QtWidgets.QWidget(Form)
        self.full_widget.setGeometry(QtCore.QRect(10, 20, 801, 461))
        self.full_widget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.full_widget.setAutoFillBackground(False)
        self.full_widget.setStyleSheet("")
        self.full_widget.setObjectName("full_widget")
        self.background_image = QtWidgets.QLabel(self.full_widget)
        self.background_image.setGeometry(QtCore.QRect(0, 0, 801, 461))
        self.background_image.setStyleSheet("#background_image{    \n"
"    border-top-right-radius: 10px;\n"
"    border-bottom-right-radius: 10px;\n"
"    border-top: 2px solid #343434;\n"
"    border-right: 2px solid #343434;\n"
"    border-bottom: 2px solid #343434;\n"
"}\n"
"#background_image{    \n"
"    border-top-left-radius: 10px;\n"
"    border-bottom-left-radius: 10px;\n"
"    border-top: 2px solid #343434;\n"
"    border-left: 2px solid #343434;\n"
"    border-bottom: 2px solid #343434;\n"
"}")
        self.background_image.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.background_image.setText("")
        self.background_image.setPixmap(QtGui.QPixmap(":/icons/Icons/wallpaperflare.com_wallpaper.jpg"))
        self.background_image.setScaledContents(True)
        self.background_image.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.background_image.setWordWrap(False)
        self.background_image.setObjectName("background_image")
        self.black_background = QtWidgets.QLabel(self.full_widget)
        self.black_background.setGeometry(QtCore.QRect(0, 0, 401, 461))
        self.black_background.setStyleSheet("#black_background{\n"
"    background-color: rgba(0, 0, 0, 130);\n"
"}\n"
"#black_background{\n"
"    border-top-left-radius: 10px;\n"
"    border-bottom-left-radius: 10px;\n"
"    border-top: 2px solid #343434;\n"
"    border-left: 2px solid #343434;\n"
"    border-bottom: 2px solid #343434;\n"
"}")
        self.black_background.setText("")
        self.black_background.setObjectName("black_background")
        self.black_background_2 = QtWidgets.QLabel(self.full_widget)
        self.black_background_2.setGeometry(QtCore.QRect(400, 0, 401, 461))
        self.black_background_2.setStyleSheet("#black_background_2{\n"
"    background-color: rgba(102, 102, 102, 130);;\n"
"}\n"
"#black_background_2{\n"
"    border-top-right-radius: 10px;\n"
"    border-bottom-right-radius: 10px;\n"
"    border-top: 2px solid #343434;\n"
"    border-right: 2px solid #343434;\n"
"    border-bottom: 2px solid #343434;\n"
"}")
        self.black_background_2.setText("")
        self.black_background_2.setScaledContents(True)
        self.black_background_2.setObjectName("black_background_2")
        self.func_widget = QtWidgets.QStackedWidget(self.full_widget)
        self.func_widget.setGeometry(QtCore.QRect(400, 0, 401, 461))
        self.func_widget.setStyleSheet("#func_widget{\n"
"    border-top-right-radius: 10px;\n"
"    border-bottom-right-radius: 10px;\n"
"    border-top: 2px solid #343434;\n"
"    border-right: 2px solid #343434;\n"
"    bodrer-bottom: 2px solid #343434;\n"
"}\n"
"#func_widget QLineEdit{\n"
"    border: 1px solid #b9b9b9;\n"
"    border-radius: 5px;\n"
"    padding: 5px 10px;\n"
"    font-size: 15px;\n"
"}\n"
"#func_widget QLineEdit:focus{\n"
"    border-color: 5500ff;\n"
"}\n"
"#func_widget QPushButton{\n"
"    font-size: 12cm;\n"
"    border-radius: 5px;\n"
"    color: #fff;\n"
"}\n"
"#func_widget QPushButton:pressed{\n"
"    padding-left: 10px;\n"
"}\n"
"#login_btn, #create_btn{\n"
"    \n"
"    background-color: #3554d1;\n"
"}\n"
"#login_btn:hover, #create_btn:hover, #login_btn:pressed, #create_btn:pressed{\n"
"    \n"
"    background-color: #0000ff;\n"
"}\n"
"#exit_btn{\n"
"    \n"
"    background-color: #d10000;\n"
"}\n"
"#exit_btn:hover, #exit_btn:pressed{\n"
"    \n"
"    background-color: #910000;\n"
"}\n"
"#register_btn, #back_btn{\n"
"    \n"
"    background-color: #55aa70;\n"
"}\n"
"#register_btn:hover, #back_btn:hover, #register_btn:pressed, #back_btn:pressed{\n"
"    \n"
"    background-color: #3aad00;\n"
"}")
        self.func_widget.setObjectName("func_widget")
        self.login_page = QtWidgets.QWidget()
        self.login_page.setObjectName("login_page")
        self.widget = QtWidgets.QWidget(self.login_page)
        self.widget.setGeometry(QtCore.QRect(40, 30, 321, 301))
        self.widget.setObjectName("widget")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_5.setContentsMargins(0, 20, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.login_lbl = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        self.login_lbl.setFont(font)
        self.login_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.login_lbl.setObjectName("login_lbl")
        self.verticalLayout_5.addWidget(self.login_lbl)
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.username_lbl1 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.username_lbl1.setFont(font)
        self.username_lbl1.setObjectName("username_lbl1")
        self.verticalLayout_4.addWidget(self.username_lbl1)
        self.username_edit1 = QtWidgets.QLineEdit(self.widget)
        self.username_edit1.setClearButtonEnabled(True)
        self.username_edit1.setObjectName("username_edit1")
        self.verticalLayout_4.addWidget(self.username_edit1)
        self.verticalLayout_5.addLayout(self.verticalLayout_4)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.password_lbl1 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.password_lbl1.setFont(font)
        self.password_lbl1.setObjectName("password_lbl1")
        self.verticalLayout_3.addWidget(self.password_lbl1)
        self.password_edit1 = QtWidgets.QLineEdit(self.widget)
        self.password_edit1.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password_edit1.setClearButtonEnabled(True)
        self.password_edit1.setObjectName("password_edit1")
        self.verticalLayout_3.addWidget(self.password_edit1)
        self.verticalLayout_5.addLayout(self.verticalLayout_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.exit_btn = QtWidgets.QPushButton(self.widget)
        self.exit_btn.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.exit_btn.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/Icons/8527022301627270244-128.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.exit_btn.setIcon(icon)
        self.exit_btn.setObjectName("exit_btn")
        self.horizontalLayout_2.addWidget(self.exit_btn)
        self.register_btn = QtWidgets.QPushButton(self.widget)
        self.register_btn.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.register_btn.setFont(font)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/Icons/8720809901557740366-128.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.register_btn.setIcon(icon1)
        self.register_btn.setObjectName("register_btn")
        self.horizontalLayout_2.addWidget(self.register_btn)
        self.login_btn = QtWidgets.QPushButton(self.widget)
        self.login_btn.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.login_btn.setFont(font)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/Icons/sign-out-alt.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.login_btn.setIcon(icon2)
        self.login_btn.setObjectName("login_btn")
        self.horizontalLayout_2.addWidget(self.login_btn)
        self.verticalLayout_5.addLayout(self.horizontalLayout_2)
        self.func_widget.addWidget(self.login_page)
        self.register_page = QtWidgets.QWidget()
        self.register_page.setObjectName("register_page")
        self.widget1 = QtWidgets.QWidget(self.register_page)
        self.widget1.setGeometry(QtCore.QRect(40, 30, 321, 351))
        self.widget1.setObjectName("widget1")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.widget1)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_14 = QtWidgets.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        self.label_14.setFont(font)
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.verticalLayout_8.addWidget(self.label_14)
        spacerItem1 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(-1, 20, -1, -1)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.username_lbl2 = QtWidgets.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.username_lbl2.setFont(font)
        self.username_lbl2.setObjectName("username_lbl2")
        self.verticalLayout_6.addWidget(self.username_lbl2)
        self.email_lbl = QtWidgets.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.email_lbl.setFont(font)
        self.email_lbl.setObjectName("email_lbl")
        self.verticalLayout_6.addWidget(self.email_lbl)
        self.phone_lbl = QtWidgets.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.phone_lbl.setFont(font)
        self.phone_lbl.setObjectName("phone_lbl")
        self.verticalLayout_6.addWidget(self.phone_lbl)
        self.address_lbl = QtWidgets.QLabel(self.widget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.address_lbl.sizePolicy().hasHeightForWidth())
        self.address_lbl.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.address_lbl.setFont(font)
        self.address_lbl.setObjectName("address_lbl")
        self.verticalLayout_6.addWidget(self.address_lbl)
        self.password_lbl2 = QtWidgets.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.password_lbl2.setFont(font)
        self.password_lbl2.setObjectName("password_lbl2")
        self.verticalLayout_6.addWidget(self.password_lbl2)
        self.horizontalLayout_4.addLayout(self.verticalLayout_6)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.username_edit2 = QtWidgets.QLineEdit(self.widget1)
        self.username_edit2.setClearButtonEnabled(True)
        self.username_edit2.setObjectName("username_edit2")
        self.verticalLayout_7.addWidget(self.username_edit2)
        self.email_edit = QtWidgets.QLineEdit(self.widget1)
        self.email_edit.setClearButtonEnabled(True)
        self.email_edit.setObjectName("email_edit")
        self.verticalLayout_7.addWidget(self.email_edit)
        self.phone_edit = QtWidgets.QLineEdit(self.widget1)
        self.phone_edit.setClearButtonEnabled(True)
        self.phone_edit.setObjectName("phone_edit")
        self.verticalLayout_7.addWidget(self.phone_edit)
        self.address_edit = QtWidgets.QLineEdit(self.widget1)
        self.address_edit.setClearButtonEnabled(True)
        self.address_edit.setObjectName("address_edit")
        self.verticalLayout_7.addWidget(self.address_edit)
        self.password_edit2 = QtWidgets.QLineEdit(self.widget1)
        self.password_edit2.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password_edit2.setClearButtonEnabled(True)
        self.password_edit2.setObjectName("password_edit2")
        self.verticalLayout_7.addWidget(self.password_edit2)
        self.horizontalLayout_4.addLayout(self.verticalLayout_7)
        self.verticalLayout_8.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.back_btn = QtWidgets.QPushButton(self.widget1)
        self.back_btn.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.back_btn.setFont(font)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/Icons/8588628601530177257-128.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.back_btn.setIcon(icon3)
        self.back_btn.setObjectName("back_btn")
        self.horizontalLayout_3.addWidget(self.back_btn)
        self.create_btn = QtWidgets.QPushButton(self.widget1)
        self.create_btn.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.create_btn.setFont(font)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/Icons/7337780431582534641-128.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.create_btn.setIcon(icon4)
        self.create_btn.setObjectName("create_btn")
        self.horizontalLayout_3.addWidget(self.create_btn)
        self.verticalLayout_8.addLayout(self.horizontalLayout_3)
        self.func_widget.addWidget(self.register_page)
        self.widget_2 = QtWidgets.QWidget(self.full_widget)
        self.widget_2.setGeometry(QtCore.QRect(0, 0, 401, 461))
        self.widget_2.setStyleSheet("#widget_2{\n"
"    border-top-left-radius: 10px;\n"
"    border-bottom-left-radius: 10px;\n"
"    border-top: 2px solid #343434;\n"
"    border-left: 2px solid #343434;\n"
"    border-bottom: 2px solid #343434;\n"
"}")
        self.widget_2.setObjectName("widget_2")
        self.widget2 = QtWidgets.QWidget(self.widget_2)
        self.widget2.setGeometry(QtCore.QRect(40, 100, 361, 361))
        self.widget2.setObjectName("widget2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.text_lbl1 = QtWidgets.QLabel(self.widget2)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.text_lbl1.setFont(font)
        self.text_lbl1.setStyleSheet("#text_lbl1{\n"
"    color: rgba(203, 203, 203, 180);\n"
"    background-color: none;\n"
"}")
        self.text_lbl1.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.text_lbl1.setObjectName("text_lbl1")
        self.verticalLayout_2.addWidget(self.text_lbl1)
        self.text_lbl2 = QtWidgets.QLabel(self.widget2)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.text_lbl2.setFont(font)
        self.text_lbl2.setStyleSheet("#text_lbl2{\n"
"    \n"
"    color: rgba(203, 203, 203, 180);\n"
"    background-color: none;\n"
"}")
        self.text_lbl2.setObjectName("text_lbl2")
        self.verticalLayout_2.addWidget(self.text_lbl2)
        self.text_lbl3 = QtWidgets.QLabel(self.widget2)
        font = QtGui.QFont()
        font.setPointSize(32)
        self.text_lbl3.setFont(font)
        self.text_lbl3.setStyleSheet("#text_lbl3{\n"
"    \n"
"    color: rgba(255, 255, 255, 250);\n"
"    background-color: none;\n"
"}")
        self.text_lbl3.setObjectName("text_lbl3")
        self.verticalLayout_2.addWidget(self.text_lbl3)
        self.text_lbl4 = QtWidgets.QLabel(self.widget2)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.text_lbl4.setFont(font)
        self.text_lbl4.setStyleSheet("#text_lbl4{\n"
"    color: rgba(203, 203, 203, 180);\n"
"    background-color: none;\n"
"}")
        self.text_lbl4.setObjectName("text_lbl4")
        self.verticalLayout_2.addWidget(self.text_lbl4)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.describe_lbl1 = QtWidgets.QLabel(self.widget2)
        self.describe_lbl1.setStyleSheet("#describe_lbl1{\n"
"    color: rgba(203, 203, 203, 160);\n"
"    background-color: none;\n"
"}\n"
"")
        self.describe_lbl1.setObjectName("describe_lbl1")
        self.verticalLayout.addWidget(self.describe_lbl1)
        self.describe_lbl2 = QtWidgets.QLabel(self.widget2)
        self.describe_lbl2.setStyleSheet("#describe_lbl2{\n"
"    color: rgba(203, 203, 203, 160);\n"
"    background-color: none;\n"
"}")
        self.describe_lbl2.setObjectName("describe_lbl2")
        self.verticalLayout.addWidget(self.describe_lbl2)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.widget3 = QtWidgets.QWidget(self.widget_2)
        self.widget3.setGeometry(QtCore.QRect(40, 0, 321, 101))
        self.widget3.setObjectName("widget3")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget3)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.logo_image = QtWidgets.QLabel(self.widget3)
        self.logo_image.setMaximumSize(QtCore.QSize(500, 500))
        self.logo_image.setText("")
        self.logo_image.setPixmap(QtGui.QPixmap(":/icons/Icons/toyota-car-logo-6961 (1).png"))
        self.logo_image.setScaledContents(True)
        self.logo_image.setObjectName("logo_image")
        self.horizontalLayout.addWidget(self.logo_image)
        self.logo_name = QtWidgets.QLabel(self.widget3)
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setBold(True)
        self.logo_name.setFont(font)
        self.logo_name.setObjectName("logo_name")
        self.horizontalLayout.addWidget(self.logo_name)

        self.retranslateUi(Form)
        self.func_widget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.login_lbl.setText(_translate("Form", "L o g i n"))
        self.username_lbl1.setText(_translate("Form", "Username"))
        self.password_lbl1.setText(_translate("Form", "Password"))
        self.exit_btn.setText(_translate("Form", "Exite"))
        self.register_btn.setText(_translate("Form", "Register"))
        self.login_btn.setText(_translate("Form", "Login"))
        self.label_14.setText(_translate("Form", "R g i s t e r"))
        self.username_lbl2.setText(_translate("Form", "Username"))
        self.email_lbl.setText(_translate("Form", "Email Address"))
        self.phone_lbl.setText(_translate("Form", "Phone Number"))
        self.address_lbl.setText(_translate("Form", "Address"))
        self.password_lbl2.setText(_translate("Form", "Password"))
        self.back_btn.setText(_translate("Form", "Back"))
        self.create_btn.setText(_translate("Form", "Create"))
        self.text_lbl1.setText(_translate("Form", "Toyota Cars Marketplace"))
        self.text_lbl2.setText(_translate("Form", "Buy & Sell Your"))
        self.text_lbl3.setText(_translate("Form", "Toyota Car Easily"))
        self.text_lbl4.setText(_translate("Form", "With Toyota Market"))
        self.describe_lbl1.setText(_translate("Form", "Our App Will Help You To Achieve The Best"))
        self.describe_lbl2.setText(_translate("Form", "Experience Of Buying And Selling Your Car"))
        self.logo_name.setText(_translate("Form", "TOYOTA"))
import login_resource


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
